version: '3'

services:
    api:
        build:
          context: ./api
          dockerfile: Dockerfile
        image: guardrailsapi
        container_name: guardrailsapi
        restart: unless-stopped
        network_mode: host
    dashboard:
        build:
          context: ./dashboard
          dockerfile: Dockerfile
        image: guardrailsdashboard
        container_name: guardrailsdashboard
        restart: unless-stopped
        network_mode: host
