version: '3'

services:
    api:
        build:
          context: ./api
          dockerfile: Dockerfile
        image: guardrailsapi
        ports:
            - "4000:4000"
        container_name: guardrailsapi
        restart: unless-stopped
        depends_on:
            - mongo
    dashboard:
        build:
          context: ./dashboard
          dockerfile: Dockerfile
        image: guardrailsdashboard
        container_name: guardrailsdashboard
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - api
    mongo:
        image: mongo
        container_name: db
        restart: always
